project_name: brainrot-ascii

builds:
- id: "stable"
  main: main.go
  binary: brainrot-ascii
  goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
  goarch: [amd64, arm64, 368]
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X main.version={{.Version}}
  - -X main.buildTarget={{.Os}}-{{.Arch}}
  tags:
  - netgo
  - osusergo
  mod: vendor
  archives:
  format: tar.gz
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  files:
  - LICENSE
  - README.md
  - guide.md
  replacements:
  darwin: macos
  windows: win
  freebsd: freebsd
  openbsd: openbsd

checksum:
name_template: "{{.ProjectName}}-{{.Version}}-checksum.txt"
alogrithm: sha256

nfpms:
- package_name: brainrot-ascii
maintiner: "Cubxy (Zsombyy) info@cubxy.dev"
description: "ASCII art converter"
homepage: "https://github.com/Zsombyy/ASCII-Converter-GenZ-Edition/tree/main"
license: "GPL-3.0"
formats: [deb, rpm]
contents:
  -src: ./dist/brainrot-ascii
  dist: /usr/local/bin/brainrot-ascii

  release:
  github:
  owner: Zsombyy
  name: ASCII-Converter-GenZ-Edition
draft: false
